version: '3.8'

services:
  crawler:
    image: ${CRAWLER_IMAGE}
    container_name: strandnerd-crawler
    restart: unless-stopped
    env_file: .env
    volumes:
      # Bind local tenants.yml configuration file
      - ./tenants.yml:/app/tenants.yml:ro
    command: ["-interval", "300"]
    extra_hosts:
      - "host.docker.internal:host-gateway"
    labels:
      - "project=strandnerd"
      - "service=crawler"
      - "environment=production"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.25'
