version: '3.8'

services:
  crawler:
    image: strandnerd-crawler:latest
    container_name: strandnerd-crawler
    restart: unless-stopped
    env_file: .env
    command: ["-interval", "300"]
    labels:
      - "project=strandnerd"
      - "service=crawler"
      - "environment=production"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.25'
