version: '3.8'

services:
  crawler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: strandnerd-crawler
    restart: unless-stopped
    volumes:
      - ./tenants.yml:/app/tenants.yml:ro
    environment:
      # CMS API Configuration (legacy - fallback if no tenants.yml)
      CMS_BASE_URL: ${CMS_BASE_URL:-http://localhost}
      ACCESS_TOKEN: ${ACCESS_TOKEN}
      
      # Crawler Configuration  
      LOG_LEVEL: ${LOG_LEVEL:-info}
      FEED_REFRESH_INTERVAL: ${FEED_REFRESH_INTERVAL:-5}
      REQUEST_TIMEOUT: ${REQUEST_TIMEOUT:-30}
      MAX_CONCURRENT_CRAWLS: ${MAX_CONCURRENT_CRAWLS:-3}
      USER_AGENT: ${USER_AGENT:-SN/1.0}
      OPENAI_API_KEY: ${OPENAI_API_KEY}

      # Proxy Configuration
      PROXY_HOST: ${PROXY_HOST}
      PROXY_AUTH: ${PROXY_AUTH}
      
    
    # Default: run continuously every 5 minutes (300 seconds)
    # Override with: docker-compose run --rm crawler -once
    command: ["-interval", "300"]
    
    # Add labels for easier management
    labels:
      - "project=strandnerd"
      - "service=crawler"
      - "environment=production"

# No networks needed since this is a standalone background service
